# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicstore', '0002_song_song_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='desc',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
